// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq7R5dpp2UVJmXFkEZ2tTbzhbTHP80esY',
    appId: '1:728263966452:web:389a741f33bb81229928a1',
    messagingSenderId: '728263966452',
    projectId: 'my-recipe-ee064',
    authDomain: 'my-recipe-ee064.firebaseapp.com',
    storageBucket: 'my-recipe-ee064.appspot.com',
    measurementId: 'G-VGDX0PF811',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoH2xyaV1djmB1fD3IMGiieugirc9xl4o',
    appId: '1:728263966452:android:6bc044fba5350d149928a1',
    messagingSenderId: '728263966452',
    projectId: 'my-recipe-ee064',
    storageBucket: 'my-recipe-ee064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFDQP50PBbcPwoFMqzFWoNC8JSFj1DA8',
    appId: '1:728263966452:ios:27f27c348f50839c9928a1',
    messagingSenderId: '728263966452',
    projectId: 'my-recipe-ee064',
    storageBucket: 'my-recipe-ee064.appspot.com',
    iosClientId: '728263966452-khj9jggic918nc469hm0tp36mnqvv2fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqFDQP50PBbcPwoFMqzFWoNC8JSFj1DA8',
    appId: '1:728263966452:ios:27f27c348f50839c9928a1',
    messagingSenderId: '728263966452',
    projectId: 'my-recipe-ee064',
    storageBucket: 'my-recipe-ee064.appspot.com',
    iosClientId: '728263966452-khj9jggic918nc469hm0tp36mnqvv2fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myRecipe',
  );
}
